### ISSUE TITLE
hab svc start options changed in 0.56.1, broke master branch builds

### ISSUE THREAD

**Issue by jkerry** [chef-cookbooks/habitat#103]
### Cookbook version
0.56.1

### Chef-client version
N/A

### Platform Details
All

### Scenario:
The habitat 0.56.0 supervisor release changed a number of user interface components that need to be changed in resources here, in particular the hab_service start action has had a large number of fields removed in place of the load action. Those items should be removed from the start action and documentation

### Steps to Reproduce:
N/A

### Expected Result:
N/A

### Actual Result:
n/A

**Comment by jkerry** [comment]
Note:  master branch build appear to pass now in travis.  Failing build is noted here:
https://travis-ci.org/chef-cookbooks/habitat/builds/388870569

**Comment by jtimberman** [comment]
@jkerry Can you provide some more information about this issue? Is it still an issue? I can't reproduce any exceptions with the kitchen tests using the dokken config on my local machine.

**Comment by jkerry** [comment]
I'm glad the build is passing then and that jives with my pull request passing the build. Outside the broken build there's an update to remove capability from the service :start action.

https://www.habitat.sh/docs/habitat-cli/#hab-svc-start

the documentation indicates that most of the functionality in hab svc start has been removed in 0.56.0 and moved to hab svc load, leaving the start action to only start a loaded but stopped service.

**Comment by jonlives** [comment]
I can replicate this too on supervisor versions 0.56.1 and 0.57.0, using the latest supermarket release of the habitat cookbook. For reference, here's the full output of the run failure:

```
* hab_service[jonlives/compliance] action start
    * execute[hab svc start jonlives/compliance --channel stable --strategy at-once --topology standalone] action run
      
      ================================================================================
      Error executing action `run` on resource 'execute[hab svc start jonlives/compliance --channel stable --strategy at-once --topology standalone]'
      ================================================================================
      
      Mixlib::ShellOut::ShellCommandFailed
      ------------------------------------
      Expected process to exit with [0], but received '1'
      ---- Begin output of hab svc start jonlives/compliance --channel stable --strategy at-once --topology standalone ----
      STDOUT: 
      STDERR: error: Found argument '--channel' which wasn't expected, or isn't valid in this context
      
      USAGE:
          hab svc start [OPTIONS] <PKG_IDENT>
      
      For more information try --help
      ---- End output of hab svc start jonlives/compliance --channel stable --strategy at-once --topology standalone ----
      Ran hab svc start jonlives/compliance --channel stable --strategy at-once --topology standalone returned 1
      
      Resource Declaration:
      ---------------------
      # In /hab/svc/chef-base/data/cache/cache/cookbooks/habitat/resources/service.rb
      
      101:   execute "hab svc start #{new_resource.service_name} #{sup_options.join(' ')}" unless current_resource.running
      102: end
      
      Compiled Resource:
      ------------------
      # Declared in /hab/svc/chef-base/data/cache/cache/cookbooks/habitat/resources/service.rb:101:in `block in class_from_file'
      
      execute("hab svc start jonlives/compliance --channel stable --strategy at-once --topology standalone") do
        action [:run]
        default_guard_interpreter :execute
        command "hab svc start jonlives/compliance --channel stable --strategy at-once --topology standalone"
        backup 5
        declared_type :execute
        cookbook_name "applications"
        domain nil
        user nil
      end
      
      System Info:
      ------------
      chef_version=14.1.21
      platform=amazon
      platform_version=2018.03
      ruby=ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]
      program_name=/hab/pkgs/chef/chef-client/14.1.21/20180521162341/bin/chef-client
      executable=/hab/pkgs/chef/chef-client/14.1.21/20180521162341/bin/chef-client
      
    
    ================================================================================
    Error executing action `start` on resource 'hab_service[jonlives/compliance]'
    ================================================================================
    
    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    execute[hab svc start jonlives/compliance --channel stable --strategy at-once --topology standalone] (/hab/svc/chef-base/data/cache/cache/cookbooks/habitat/resources/service.rb line 101) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
    ---- Begin output of hab svc start jonlives/compliance --channel stable --strategy at-once --topology standalone ----
    STDOUT: 
    STDERR: error: Found argument '--channel' which wasn't expected, or isn't valid in this context
    
    USAGE:
        hab svc start [OPTIONS] <PKG_IDENT>
    
    For more information try --help
    ---- End output of hab svc start jonlives/compliance --channel stable --strategy at-once --topology standalone ----
    Ran hab svc start jonlives/compliance --channel stable --strategy at-once --topology standalone returned 1
    
    Resource Declaration:
    ---------------------
    # In /hab/svc/chef-base/data/cache/cache/cookbooks/applications/recipes/default.rb
    
     26:   hab_service application do
     27:     strategy      'at-once'
     28:     topology      'standalone'
     29:     action        :start
     30:   end
     31: 
    
    Compiled Resource:
    ------------------
    # Declared in /hab/svc/chef-base/data/cache/cache/cookbooks/applications/recipes/default.rb:26:in `block in from_file'
    
    hab_service("jonlives/compliance") do
      action [:start]
      default_guard_interpreter :default
      declared_type :hab_service
      cookbook_name "applications"
      recipe_name "default"
      strategy "at-once"
      topology "standalone"
    end
    
    System Info:
    ------------
    chef_version=14.1.21
    platform=amazon
    platform_version=2018.03
    ruby=ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]
    program_name=/hab/pkgs/chef/chef-client/14.1.21/20180521162341/bin/chef-client
    executable=/hab/pkgs/chef/chef-client/14.1.21/20180521162341/bin/chef-client
    

Running handlers:
[2018-06-19T09:20:59+00:00] ERROR: Running exception handlers
```

**Comment by jonlives** [comment]
This can also be replicated by running ```kitchen converge service-ubuntu-1404``` (haven't tested other images yet) on the cookbook. Will start taking a look at fixing this.
