### ISSUE TITLE
undefined method `clean_array' error on `hab_package` invocation

### ISSUE THREAD

**Issue by jamesc** [chef-cookbooks/habitat#109]
### Cookbook version
0.57.0

### Chef-client version
14.3.37

### Platform Details
Ubuntu 16.04 (Azure)

### Scenario:
Simple installation of hab packaged national parks (https://github.com/chef-partners/hab_national_parks)

### Steps to Reproduce:
Using Chef run on checked out version of cookbook e.g. 

```
chef-run  hab-test.westus2.cloudapp.azure.com hab_national_parks   --sudo --user james
```

### Expected Result:
Supervisor and packages installed

### Actual Result:
```
 chef-run  hab-test.westus2.cloudapp.azure.com hab_national_parks   --sudo --user james
[\] Generating local policyfile...WARN: scripts cookbook missing metadata or no name field, skipping
[✔] Generated local policyfile
[✔] [hab-test.westus2.cloudapp.azure.com] Connected.
[✔] [hab-test.westus2.cloudapp.azure.com] Chef client version 14.3.37 already installed on target.
[✖] [hab-test.westus2.cloudapp.azure.com] Failed to converge target.

CHEFCCR002

The converge of the remote host failed for the
following reason:

  undefined method `clean_array' for #<Chef::Provider::Package::Hart:0x0000000003e91b70>

If you are not able to resolve this issue, please contact Chef support
at beta@chef.io

```

Logs:
```
Synchronizing Cookbooks:
  - hab_national_parks (0.1.1)
  - habitat (0.57.0)
Installing Cookbook Gems:
Compiling Cookbooks...
Converging 4 resources
Recipe: hab_national_parks::default
  * hab_install[install habitat] action install
    * apt_package[curl, tar] action install (up to date)
    * linux_user[hab] action create (up to date)
     (up to date)
  * hab_sup_systemd[default] action run
    * hab_install[default] action install
      * apt_package[curl, tar] action install (up to date)
      * linux_user[hab] action create (up to date)
       (up to date)
    * hab_package[core/hab-sup] action install

      ================================================================================
      Error executing action `install` on resource 'hab_package[core/hab-sup]'
      ================================================================================

      NoMethodError
      -------------
      undefined method `clean_array' for #<Chef::Provider::Package::Hart:0x0000000003e91b70>

      Cookbook Trace:
      ---------------
      /var/chef-workstation/cache/cookbooks/habitat/libraries/provider_hab_package.rb:90:in `hab'
      /var/chef-workstation/cache/cookbooks/habitat/libraries/provider_hab_package.rb:144:in `installed_version'
      /var/chef-workstation/cache/cookbooks/habitat/libraries/provider_hab_package.rb:139:in `block in current_versions'
      /var/chef-workstation/cache/cookbooks/habitat/libraries/provider_hab_package.rb:138:in `map'
      /var/chef-workstation/cache/cookbooks/habitat/libraries/provider_hab_package.rb:138:in `current_versions'
      /var/chef-workstation/cache/cookbooks/habitat/libraries/provider_hab_package.rb:59:in `load_current_resource'

      Resource Declaration:
      ---------------------
      # In /var/chef-workstation/cache/cookbooks/habitat/libraries/resource_hab_sup.rb

       43:         hab_package 'core/hab-sup' do
       44:           bldr_url new_resource.bldr_url if new_resource.bldr_url
       45:         end
       46:       end


```

**Comment by st-h** [comment]
I have been running into this today.

To fix this I modified this line

https://github.com/chef-cookbooks/habitat/blob/14fd861ab99ea861d0c8697ca5c7c0c9fb0fbf8e/libraries/provider_hab_package.rb#L90

to

`shell_out_with_timeout!(*Chef::Mixin::ShellOut.clean_array('hab', *command))`

Haven't had time to look into if this is the right way to fix this, however it happily converges again.

**Comment by lamont-granquist** [comment]
that'll break on every other version of chef-client.

**Comment by jamesc** [comment]
[from lamont in PR]

chef/chef#7477

that'll unbreak it with the old API, but it will throw multiple deprecation warnings now (on the use of both shell_out_with_timeout and clean_array, both of which are deprecated).

the correct code is just:

shell_out!('hab', *command)
but that will not work on chef < 14.3.x

**Comment by lamont-granquist** [comment]
we still need to track the deprecation

**Comment by lamont-granquist** [comment]
not entirely surprisingly, clean_array was my fault in the first place:  9d2af929caa57970665d4cec4249dae0caa5181c
