### ISSUE TITLE
`clean_array` error when using `chef-client` version 12.13.37

### ISSUE THREAD

**Issue by smartb-pair** [chef-cookbooks/habitat#27]
We are using the `smartb/devpi-server` Habitat package, available in the public depot. Using the latest stable `chef-client` release seems to fix this - maybe docs should make clear if this there is a version constraint around `chef-client` version?:
```
* hab_package[smartb/devpi-server] action install

           ================================================================================
           Error executing action `install` on resource 'hab_package[smartb/devpi-server]'
           ================================================================================

           NoMethodError
           -------------
           undefined method `clean_array' for #<Chef::Provider::Package::Hart:0x00000003744c28>

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/habitat/libraries/provider_hab_package.rb:91:in `hab'
           /tmp/kitchen/cache/cookbooks/habitat/libraries/provider_hab_package.rb:150:in `get_installed_version'
           /tmp/kitchen/cache/cookbooks/habitat/libraries/provider_hab_package.rb:144:in `block in get_current_versions'
           /tmp/kitchen/cache/cookbooks/habitat/libraries/provider_hab_package.rb:143:in `map'
           /tmp/kitchen/cache/cookbooks/habitat/libraries/provider_hab_package.rb:143:in `get_current_versions'
           /tmp/kitchen/cache/cookbooks/habitat/libraries/provider_hab_package.rb:60:in `load_current_resource'

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/devpi_smartb/recipes/default.rb

             8: hab_package "smartb/devpi-server"
             9:

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/devpi_smartb/recipes/default.rb:8:in `from_file'

           hab_package("smartb/devpi-server") do
             package_name "smartb/devpi-server"
             action [:install]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :hab_package
             cookbook_name "devpi_smartb"
             recipe_name "default"
             depot_url "https://willem.habitat.sh/v1/depot"
           end

           Platform:
           ---------
           x86_64-linux


       Running handlers:
       [2016-12-19T10:01:28+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2016-12-19T10:01:28+00:00] ERROR: Exception handlers complete
       Chef Client failed. 3 resources updated in 12 seconds
       [2016-12-19T10:01:28+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2016-12-19T10:01:28+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2016-12-19T10:01:28+00:00] ERROR: hab_package[smartb/devpi-server] (devpi_smartb::default line 8) had an error: NoMethodError: undefined method `clean_array' for #<Chef::Provider::Package::Hart:0x00000003744c28>
       [2016-12-19T10:01:28+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Converge failed on instance <default-ubuntu-1604>.  Please see .kitchen/logs/default-ubuntu-1604.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

**Comment by lamont-granquist** [comment]
not a bug
